# Generated by Django 4.2.16 on 2024-10-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='search_period',
            field=models.CharField(max_length=50),
        ),
    ]
